[package]
name = "bootloader"
version = "0.1.0"
authors = ["Valentin B. <valentin.be@protonmail.com>"]
edition = "2018"

[package.metadata.cargo-xbuild]
memcpy = true
sysroot_path = "target/sysroot"

[dependencies]
libtegra = { git = "https://github.com/mirage-rs/libtegra.git" }
